### ISSUE TITLE
Generate a term frequency model for the entirety of the SUMO corpus

### ISSUE THREAD

**Issue by mlopatka** [mlopatka/CANOSP2020#4]
Parse the entire SUMO corpus via the Kitsune API and store a local copy so that we are not hitting the API constantly.
Count the word frequency across the entire corpus.

**Comment by ExiaSR** [comment]
Close in favor https://drive.google.com/file/d/1usS1xml1iQmNZ0tSLwY2k4czUNEfE99u/view?usp=sharing
