### ISSUE TITLE
Determine a useful IDF (global term frequency model) for normalizing term frequency for support tickets

### ISSUE THREAD

**Issue by mlopatka** [mlopatka/CANOSP2020#45]
Possible normalization can be performed using the entirety of the SUMO corpus or a subset. Some strategies may be to:

- use a sample of **recent** tickets
- use a random subset of tickets
- use a subset of tickets that is selected to ensure balanced representation of active fx versions
- use a subset of tickets corresponding to only the current release version of Firefox

This issue should be closed by the production of a notebook comparing the impact of different strategies and the downstream impact on some primitive models. A decision about what normalization strategy is advocated for should be specified.

**Comment by Ana16boo** [comment]
Should we close this issue? Or is it still relevant to our problem?
