### ISSUE TITLE
Manually annotate 100 support tickets with free form text tags

### ISSUE THREAD

**Issue by mlopatka** [mlopatka/CANOSP2020#48]
This process should be manually completed by EVERY contributor before this issue can be closed. Please use the comments section here to track progress of each participants' completion of the 100.

**Comment by mlopatka** [comment]
100 more questions for manual tagging have been added [here](https://github.com/mlopatka/CANOSP2020/blob/master/20january2020-100-random-canosp-issue-46-ff70-ff71-ff72.csv)
- [ ] @mlopatka tag the 100 questions
- [ ] @rtanglao  tag the 100 questions
- [ ] @ExiaSR tag the 100 questions
- [ ] @konantian tag the 100 questions
- [ ] @Ana16boo tag the 100 questions
- [ ] @willfenton tag the 100 questions

**Comment by rtanglao** [comment]
i added link to joni's tagged 100 questions: https://docs.google.com/spreadsheets/d/1OxuxTyyqKH9HNGt3VzRvE0JwPdtJKXa2tl_l1KVtmEE/edit#gid=0
