### ISSUE TITLE
Refactor a branch of CrowdTruth to remove use of timing

### ISSUE THREAD

**Issue by mlopatka** [mlopatka/CANOSP2020#50]
The CrowdTruth library uses the timing associated with tag attribution events as a factor for assessing tagger and tag reliability. We currently clobber this functionality by passing a uniform time value for every tag/item/tagger triplet. 

It would be ideal to remove the timing factor from the CrowdTruth code or refactor the code to optionally omit its usage in a custom fork.

**Comment by willfenton** [comment]
After looking into the CrowdTruth source code, I'm 99% sure that it doesn't use duration in computing the metrics.
My semi-scientific way of verifying this was setting random durations for each annotation and re-running the notebook, and the results were exactly the same as when all durations were 120 seconds.

**Comment by mlopatka** [comment]
It may be the case that the crrowdtruth methodology uses these timings in some other subset of its functionality than the functions we are leveraging.

Either way, if this isn't impacting our use case, then one less thing to do.
