### ISSUE TITLE
Clean up Evelyn and Brady's 100 tagged issues from 24January2020

### ISSUE THREAD

**Issue by rtanglao** [mlopatka/CANOSP2020#57]
From #48 , Mozilla employees Evelyn and Brady have completed their 2nd round of tagging and I've placed it in [this Google Drive Folder](https://drive.google.com/drive/u/0/folders/1rw-mgVf_DkDaOFWTFiLQEqCKWLULKBSE):

- [Evelyn](https://docs.google.com/spreadsheets/d/1oSUP5OUDGOP4Ut0KGpXinRv5p_ANJgrQwches2zQeDQ/edit#gid=0)
- [Brady](https://docs.google.com/spreadsheets/d/1L3jeN1MRQ45C_nfXEhhZbwbJH6KXkKjL_xLaIgNz81k/edit#gid=0)

Please:
- clean up the two google drive spreadsheets into two well formed CSVs in this github repo in the right folder

**Comment by konantian** [comment]
closed with #58
