### ISSUE TITLE
Harmonize text preprocessing workflows

### ISSUE THREAD

**Issue by mlopatka** [mlopatka/CANOSP2020#69]
Each of the different exploratory directions are using a lot of manual regex-based data cleaning.
We should consolidate that code into a utils file and use consistent prepossessing across all our different approaches.

**Comment by Ana16boo** [comment]
Lemmatization/stemming could be useful?

**Comment by mlopatka** [comment]
@ExiaSR @rtanglao @willfenton @konantian 
What else would be like to include in a generic pre-processing workflow?

**Comment by ExiaSR** [comment]
> @ExiaSR @rtanglao @willfenton @konantian
> What else would be like to include in a generic pre-processing workflow?

So far we have, lemmatization, remove stop words/punct
https://github.com/mlopatka/CANOSP2020/blob/master/canosp2020/preprocessing.py#L26

**Comment by konantian** [comment]
> @ExiaSR @rtanglao @willfenton @konantian
> What else would be like to include in a generic pre-processing workflow?

Maybe we can do the stemming as well.

**Comment by ExiaSR** [comment]
> > @ExiaSR @rtanglao @willfenton @konantian
> > What else would be like to include in a generic pre-processing workflow?
> 
> Maybe we can do the stemming as well.

I believe stemming would lose the semantic of text, properly not a good idea.

**Comment by ExiaSR** [comment]
related #51

**Comment by Ana16boo** [comment]
def pre_process(text):
    
    # lowercase
    text=text.lower()
    
    #remove tags
    text=re.sub("</?.*?>"," <> ",text)
    
    # remove special characters and digits
    text=re.sub("(\\d|\\W)+"," ",text)
    
    return text
