### ISSUE TITLE
sample file of 2000 tickets has 4 duplicates

### ISSUE THREAD

**Issue by rtanglao** [mlopatka/CANOSP2020#94]
The CSV file from #92 has duplicates:

```bash
cd ~/GIT/CANOSP2020/data
uniq -D mturk_tickets.csv | wc -l
8                                                                                      
```

**This should be 0 not 8 right?**

Please:

1. remove the duplicates
2. add a test or ensure that all 2000 tickets are unique

**Comment by willfenton** [comment]
Note: these are duplicate tickets (different id)

**Comment by rtanglao** [comment]
i will do this manually
